### ISSUE TITLE
Why use a custom Color type?

### ISSUE THREAD

**Issue by john-kelly** [MacCASOutreach/graphicsvg#1]
Why not use the [core/Color](http://package.elm-lang.org/packages/elm-lang/core/5.0.0/Color)?

**Comment by christopheranand** [comment]
For working with children with a mission to be inclusive, it was a big problem that core/Color doesn't contain pink.  If we used core/Color and added our own colours, that would make the documentation confusing for the children we teach.  Another problem is that core/Color (and we by inheritance) do not use standard HTML colour values, but it doesn't seem worth fixing things things, given how much code would break.

**Comment by john-kelly** [comment]
Thanks for the prompt response. That is exactly the information I was looking for.

**Comment by john-kelly** [comment]
I intend on using your library (or forking it) to teach children as well, so your mission resonates with me:
> For working with children with a mission to be inclusive, it was a big problem that core/Color doesn't contain pink.

I read over your response again and I have a question. You said: 

> If we used core/Color and added our own colours, that would make the documentation confusing for the children we teach.

Do you suggest that using the core/Color type would be confusing for students? It makes sense to want to add colors and/or change the default values for some colors, but why a separate type? If a student were to explore core/Color on their own, I think it would be confusing that the core/Color **did not work** as they expected it to. 

I am genuinely interested. Thanks ahead of time! 

(Additionally, I am by no means suggesting you change your library. I understand that backwards compatibility / stability is likely an important part of a teaching library. I am simply interested because I am in the unique position of choosing/creating the teaching library I will use for my class)

**Comment by christopheranand** [comment]
On Nov 22, 2016, at 6:16 PM, John Kelly <notifications@github.com> wrote:


I intend on using your library (or forking it) to teach children as well, so your mission resonates with me:

For working with children with a mission to be inclusive, it was a big problem that core/Color doesn't contain pink.

I read over your response again and I have a question. You said:

If we used core/Color and added our own colours, that would make the documentation confusing for the children we teach.

Do you suggest that using the core/Color type would be confusing for students? It makes sense to want to add colors and/or change the default values for some colors, but why a separate type? If a student were to explore core/Color on their own,
 I think it would be confusing that the core/Color did not work as they expected it to.


We are currently focussing on quantity over quality.  Most kids have no exposure to “coding” in any form.  So we are really focussed on what they can do in a couple of hours.  If pink were defined in GraphicSVG and red in Color, then we would have to explain
 something unnecessarily.


I am genuinely interested. Thanks ahead of time!
(Additionally, I am by no means suggesting you change your library. I understand that backwards compatibility / stability is likely an important part of a teaching library. I am simply interested because I am in the unique position of choosing/creating
 the teaching library I will use for my class)



At what level are you teaching?


We have a lot of code which is not on github, because it is a mess, but which you could definitely use as is, and maybe help make publishable.  We have 35 questions like this with a warp backend, and I’m hoping to have 100 by Christmas, with some semblance
 of organization.


http://macoutreach.rocks:8080/q/(199,5,42733)
