### ISSUE TITLE
Prerelease package for Elm 0.19

### ISSUE THREAD

**Issue by emmanuel** [MacCASOutreach/graphicsvg#21]
I’m teaching a high school CS class and I have been very inspired by this package and the paper (and book). I got started and played around using  the `elm-nineteen` branch via git imports (enough to convince myself that I would like to use this in my class). But I hit a bump. 

In order to defer (or even avoid) dealing with local installations of the Elm toolchain, I would like to stick with Ellie app as long as possible. Unfortunately, Ellie doesn’t appear to support git imports, so AFAICT it is not currently possible to use  the McMaster graphicsvg package in Ellie. 

I don’t know what effort is involved in publishing a pre-release package; I don’t even know if pre-releases are a thing in Elm. If it’s feasible, it would help me out a lot. 

If I can help, please let me know.

**Comment by CSchank** [comment]
Hi Emmanuel,

Thanks for reaching out. We greatly appreciate your interest and initiative. I just forked your tower defence game, which looks very cool! We would love to support you in any way we can.

We definitely have to get the package published on elm-package, but we're still fixing a few little bugs. I don't think they support pre-release packages. We have our own online IDE which currently has this pre-release installed on it. Could you please email me at schankuc [at] mcmaster [dot] ca? I can send you a test login which you can try out; if you like it, we can give you logins for you to use. If you'd prefer to use Ellie, we'll figure out how to make that possible. Perhaps we can just publish as-is (since we've been using it like this anyway!) and then release some patches later.

Best, 
Chris

**Comment by emmanuel** [comment]
Thanks Chris! 

I am intrigued to check out the McMaster online editor/IDE, thanks for the invitation (I just sent an email).

Selfishly, I would still encourage you to publish, especially if you're already using the `elm-nineteen` branch yourselves. To be fair, I have no idea what known issues remain, but I haven't seen any, and if you're getting by using that version, they can't be *that* big of issues.

Please publish, even if buggy :).

**Comment by CSchank** [comment]
Package published to elm-package as pre-release package 3.0.0.
