### ISSUE TITLE
`addOutline` before `notifyTap` or `notifyTapAt` doesn't show up

### ISSUE THREAD

**Issue by CSchank** [MacCASOutreach/graphicsvg#26]
Outline doesn't show up in this case. We should check other things used after `notify` functions as well -- others may be broken in the same way.

**Comment by CSchank** [comment]
Temporary workaround for those wondering: use `addOutline` before `notify*` in your pipes.

**Comment by GordonBGood** [comment]
This looks to be a bug that has lurked in the shadows for quite some time and just never showed up in testing.  It is caused by routines not "drilling down" recursively into containers but rather just not doing anything for certain containers that for which it is considered that processing does not apply, and these can be easily identified as the ones whose `case` statements end with a general `a -> a` used to make the function "total".  Thus, as well as `addOutline`, the following also likely have the same problem:  the old `curveHelper` and the new `repaint`.  The problem can be fixed relatively easily by just adding the handled cases to cover all of them, much as the `makeTransparent` function already does, so that for instance we add a case of `Tap userMsg sh -> Tap userMsg (addOutline style outlineClr sh)` to the `addOutline` function along with the cases for all of the other "notify"'s as well as any other special cases for other discriminated union types that may need special treatment.

I think the title of this issue is still incorrect, as the problem will show when one tries to `addOutline`, `curveHelper`, or `repaint` after any of the "notifies" or, indeed, after any function that wraps the shape in another type of shape container other than the ones specifically covered in the case statements.

**Comment by CSchank** [comment]
Resolved in 21de0aec
